name: Build and deploy Node.js app to Azure Web App - dev-sigmacloud-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Use a stable LTS version

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build --if-present && npm run test --if-present
      
      - name: Create dist folder
        run: mkdir dist

      - name: Archive project
        run: Compress-Archive -Path . -DestinationPath dist\node-app.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Clean up temp folders
        run: Remove-Item -Recurse -Force C:\local\Temp\zipdeploy

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dev-sigmacloud-app'
          slot-name: 'Production'
          package: dist\node-app.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FB49F843ED74443A690AF0668C70FBC }}
