name: Build and deploy Node.js app to Azure Web App - dev-sigmacloud-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use a stable LTS version

      - name: Check if dist directory exists
        run: |
          if (!(Test-Path -Path dist)) {
            New-Item -ItemType Directory -Path dist
          }

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npm run build
      
      - name: Lint and format code
        run: npm run lint:fix
         if ($LastExitCode -ne 0) { exit 0 }
         
      - name: Build for icon
        run: npm run icon
           if ($LastExitCode -ne 0) { exit 0 }
           
      - name: Archive project
        run: Compress-Archive -Path . -DestinationPath dist\node-app.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Clean up temp folders
        run: |
          if (Test-Path C:\local\Temp\zipdeploy) {
            Remove-Item -Recurse -Force C:\local\Temp\zipdeploy
          }

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact
        run: Expand-Archive -Path node-app.zip -DestinationPath .

      - name: Remove original .zip file
        run: Remove-Item -Path .\node-app.zip

      - name: Copy files to root
        run: |
             robocopy .\sigmacloud\ .\ /E /MOVE /IS

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dev-sigmacloud-app'
          slot-name: 'Production'
          package: .  # Use the current working directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1FB49F843ED74443A690AF0668C70FBC }}
