name: Build and deploy React.js app to Azure Web App - dev-iis-sigmacloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'  # Use a stable LTS version

      - name: Install dependencies
        run: |
          npm install
          npm install -g rollup
          npm install -g typescript

      - name: Build TypeScript files
        run: tsc

      - name: Build React app with cache busting
        run: npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip ./build/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: react-app

      - name: Unzip artifact for deployment
        run: unzip react-app.zip

      - name: Install Rollup globally
        run: npm install -g rollup

      - name: Install @rollup/rollup-linux-x64-gnu
        run: npm install @rollup/rollup-linux-x64-gnu

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp deployment source config-zip --resource-group dev-sigmacloud-app_group --name dev-iis-sigmacloud --src ./build.zip
